// Generated by CoffeeScript 1.4.0
(function() {
  var Crixalis, argv, frame, optimist, server;

  argv = (optimist = require('optimist'))["default"]('port', 8080)["default"]('limit', 256).boolean(['help', 'version']).usage(['Usage:', '    kaldr [--port <number>][--limit <number>]'].join('\n')).describe({
    version: 'Show version and exit',
    help: 'Show help and exit',
    port: 'Use specified port',
    limit: 'Concurrent connections limit'
  }).argv;

  if (argv.help) {
    optimist.showHelp();
    process.exit();
  }

  if (argv.version) {
    console.log('0.0.1');
    process.exit();
  }

  (Crixalis = require('crixalis')).router({
    methods: ['GET', 'HEAD']
  }).from('/kaldr.log').to(function() {
    if (this.cookies.message) {
      console.log(decodeURIComponent(this.cookies.message));
    }
    return this.code = 204;
  }).from('/kaldr.frame').to(function() {
    return this.body = frame;
  });

  Crixalis.on('auto', function() {
    this.headers['Connection'] = 'close';
    return this.select();
  });

  Crixalis.on('default', function() {
    if (this.is_head || this.is_get) {
      this.code = 404;
    } else {
      this.code = 405;
      this.headers['Allowed'] = 'GET, HEAD';
    }
    return this.render();
  });

  frame = "<!DOCTYPE html><script>(function (_, $) {\n	window.onhashchange = function () {\n		var data = _.hash.replace(/^#/, '')\n\n		if (data) {\n			$.cookie = 'message=' + encodeURIComponent(data)\n			Image().src = _.href.replace(/frame.*$/, 'log')\n			$.cookie = 'message=; expires=Thu, 01 Jan 1970 00:00:01 GMT;'\n			_.hash = ''\n		}\n	}\n}(location, document))</script>".replace(/\t+/g, '');

  server = require('http').createServer(Crixalis.handler).listen(argv.port).on('close', process.exit);

  server.maxConnections = argv.limit;

  process.on('SIGINT', server.close.bind(server));

  process.title = 'kaldr [' + argv.port + ']';

}).call(this);
