// Generated by CoffeeScript 1.4.0
(function() {
  var Crixalis, frame, server;

  (Crixalis = new require('crixalis')()).plugin('./plugins/compression').router({
    url: '/kaldr.log',
    methods: ['GET']
  }).to(function() {
    if (this.cookies.message) {
      console.log(decodeURIComponent(this.cookies.message));
    }
    return this.code = 204;
  }).set({
    url: '/kaldr.frame'
  }).to(function() {
    return this.body = frame;
  });

  frame = "<!DOCTYPE html>\n<script>(function (_, $) {\n	window.onhashchange = function () {\n		var data = _.hash.replace(/^#/, '')\n\n		if (data) {\n			$.cookie = 'message=' + encodeURIComponent(data)\n			Image().src = _.href.replace(/frame.*$/, 'log')\n			$.cookie = 'message=; expires=Thu, 01 Jan 1970 00:00:01 GMT;'\n			_.hash = ''\n		}\n	}\n}(location, document))</script>".replace(/\t+/g, '');

  server = require('http').createServer(Crixalis.handler()).listen(process.argv[2] || 8080).on('close', process.exit);

  process.on('SIGINT', server.close.bind(server));

}).call(this);
